var catalogs = {
    en: {
        introTitle: "Text goes to another window?",
        intro: "Use these options if typing goes to another window when the pointer leaves Search. If search works normally, leave protection off",
        whyTitle: "Why this can happen",
        why: "Some apps repeatedly request a different window size. Hyprland can then redirect keyboard input. This can affect Wine and other X11 apps",
        tryTitle: "Try these first",
        trySpace: "Give that app more room, or make its window floating",
        tryClose: "Close the app when you do not need it",
        tryWayland: "If it supports native Wayland, try its documented Wayland mode",
        protectionTitle: "If typing still gets interrupted",
        protectionWhen: "Keep keyboard input in Search, even when the pointer leaves the panel. Off by default",
        tradeoffTitle: "While protection is on",
        tradeoff: "Scrolling outside the panel is blocked, including mouse wheels and touchpads. Scrolling inside still works. Click outside or press Esc to close the panel",
        protectionScope: "Applies whenever you open Search, including the pinned compact panel. Does not hold keyboard input while you use Settings",
        warningsTitle: "Warning preferences",
        warningsHelp: "These options hide warnings only. They do not stop typing interruptions or turn on protection",
        appIgnoreLabel: "Ignore warnings for this app",

        ignoreMenu: "Ignore warnings…", ignoreBack: "Back to solutions",
        ignoreSession: "Ignore until logout", ignoreApp: "Ignore this app", ignoreAll: "Ignore all focus warnings",
        ignoreHelp: "Only warnings are muted. This does not fix the interruption or enable protection. You can restore warnings in Settings → Controls → Troubleshooting",
        sessionHelp: "Until logout or a Hyprland restart. Restarting the bar keeps this choice",
        allHelp: "Keeps warnings hidden across sessions until you turn this off",
        appHelp: "Matches this X11 application class, including future windows. Apps sharing the same class share this choice",
        detectedApps: "Apps detected during interruptions", detectedHelp: "These apps may be involved; detection does not prove the cause. You can mute warnings separately for each app",
        historyPrivacy: "This history stays on your device. Window titles and search text are not saved",
        noApps: "No apps recorded yet. An interruption can be detected without identifying its source", ignored: "Warnings ignored", warningsOn: "Warnings enabled",
        restoreApp: "Restore warnings", ignoreAppAction: "Ignore warnings", lastSeen: "Last detected: {date}",
        seenCount: "Recorded interruptions: {count}", classLabel: "Application class: {class}",
        appUncertain: "Suspected source", globalOverride: "Warnings are muted above. Turning off an app’s ignore switch will not restore its warnings until the session and global switches are also off",
        saveFailed: "Could not save this choice. Your previous settings are unchanged",
        notice: "Typing in search was interrupted", review: "Review options",
        title: "Typing was interrupted",
        dialogCause: "Try giving its window more room or making it floating. Or choose protection below",
        dialogUnknown: "Search lost keyboard input, but the source could not be identified",
        dialogUnknownHelp: "Try giving the other window more room or making it floating. You can also keep keyboard input in Search below",
        dialogApp: "Suspected app: {app}",
        dialogSessionProtection: "Until you turn it off or restart the bar. Scrolling outside pauses protection; touchpad or fast wheel input may be lost",
        activeSessionTemporary: "Enabled until you turn it off or restart the bar",
        dialogProtection: "Until that app window closes. Scrolling outside pauses protection; touchpad or fast wheel input may be lost",
        dialogKeep: "Keep focus every time",
        dialogKeepHelp: "For every search. Blocks scrolling outside the panel. Click outside or Esc closes it; turn off in Troubleshooting",
        dialogDetails: "Troubleshooting · details and settings",
        cause: "{app} may be interrupting your typing. Its window repeatedly asks for a different size. In affected Hyprland versions, this can send your keystrokes to the window under the pointer instead of WindowPeek",
        limits: "Temporary protection keeps your typing in WindowPeek. Scrolling outside the panel releases it; touchpad scrolling and fast wheel movements outside may be lost. Click the panel to resume typing, or press Esc to close it",
        alternatives: "Try giving that window more room, switching it to floating mode, or closing it when unused. More room may help if the app is trying to fit its contents. If the app supports native Wayland, its documented launch mode may also help",
        rsi: "RSI: Wine Wayland instructions (experimental)",
        scope: "Protection turns off automatically when the affected window closes",
        recoveryRetrying: "Restoring typing protection…", recoveryPaused: "Typing protection interrupted",
        recoveryUnavailable: "Typing protection is still enabled, but could not be restored. Click Retry in WindowPeek or reopen the panel",
        retry: "Retry", options: "Options", activeTitle: "Typing protection",
        activeManual: "Enabled for every search, regardless of which apps are open",
        activeTemporary: "Enabled until the approved app window closes",
        disableKeep: "Turn off typing protection",
        confirmKeepTitle: "Protect typing in every search?", confirmKeep: "Enable for every search",
        confirmKeepBehavior: "Enable this only if applications frequently interrupt your typing in Search. It blocks scrolling outside the panel; click outside or press Esc to close it",
        confirmKeepWhere: "Stays enabled until you turn off Keep search focus in Settings → Controls → Troubleshooting",
        checking: "Checking window…",
        cancel: "Continue without changes", allow: "Enable temporary protection",
        disabled: "Typing protection off", enabled: "Typing protection on", paused: "Typing protection paused — click the panel to resume",
        stop: "Turn off", ended: "Temporary protection turned off — the affected window was closed",
        stopped: "Temporary protection turned off", failed: "Temporary protection could not be continued",
        changed: "The window changed or could not be checked — please try again",
        repeated: "Typing in search keeps being interrupted",
        suggested: "If this keeps interrupting typing, consider Keep search focus in Settings → Controls → Troubleshooting",
        manualEnabled: "Typing protection on",
        settings: "Troubleshooting and alternatives",
        keep: "Keep search focus",
        when: "Turn this on if your typing goes to another window when you move the pointer outside search. Leave it off if search works normally",
        behavior: "Keeps typing in an opened search panel, including the pinned compact panel. Mouse-wheel and touchpad scrolling outside it are blocked. Scrolling inside the panel still works. Click outside or press Esc to close it",
        lifetime: "Off by default. When enabled, it applies each time you open search until you turn it off here. It does not lock focus while you use Settings",
        causes: "Some apps, including apps running through Wine, repeatedly ask for a different window size. When Hyprland keeps them tiled, it may redirect typing to the window under the pointer. Window activation rules can also interfere. An interruption alone does not tell us which app caused it",
        manualAlternatives: "Try giving the affected window more room or making it floating. You can also close it when unused, or try its documented native Wayland mode if available. More room may help if the app is trying to fit its contents; this is not a guaranteed fix",
        manualFailed: "Search focus protection could not start — normal input remains available"
    },
    pl: {
        introTitle: "Tekst trafia do innego okna?",
        intro: "Te opcje pomogą, gdy po wyjechaniu kursorem poza wyszukiwarkę tekst trafia do innego okna. Jeśli wszystko działa, pozostaw ochronę wyłączoną",
        whyTitle: "Skąd bierze się problem",
        why: "Niektóre aplikacje wielokrotnie żądają innego rozmiaru okna. Hyprland może wtedy przekierować wpisywanie. Dotyczy to aplikacji Wine i innych aplikacji X11",
        tryTitle: "Najpierw spróbuj",
        trySpace: "Daj tej aplikacji więcej miejsca lub przełącz jej okno w tryb pływający",
        tryClose: "Zamknij aplikację, jeśli jej teraz nie potrzebujesz",
        tryWayland: "Jeśli obsługuje natywny Wayland, wypróbuj tryb opisany w jej dokumentacji",
        protectionTitle: "Jeśli pisanie nadal jest przerywane",
        protectionWhen: "Zatrzymuje wpisywanie w wyszukiwarce także po wyjechaniu kursorem poza panel. Domyślnie wyłączone",
        tradeoffTitle: "Gdy ochrona jest włączona",
        tradeoff: "Przewijanie poza panelem jest zablokowane, także kółkiem myszy i touchpadem. Wewnątrz panelu nadal działa. Kliknięcie poza panelem lub Esc zamyka panel",
        protectionScope: "Działa przy każdym otwarciu wyszukiwarki, także w przypiętym panelu kompaktowym. Nie zatrzymuje wpisywania podczas korzystania z Ustawień",
        warningsTitle: "Ustawienia ostrzeżeń",
        warningsHelp: "Te opcje tylko ukrywają ostrzeżenia. Nie zapobiegają przerywaniu pisania ani nie włączają ochrony",
        appIgnoreLabel: "Ignoruj ostrzeżenia tej aplikacji",

        ignoreMenu: "Ignoruj ostrzeżenia…", ignoreBack: "Wróć do rozwiązań",
        ignoreSession: "Ignoruj do wylogowania", ignoreApp: "Ignoruj tę aplikację", ignoreAll: "Ignoruj wszystkie ostrzeżenia o fokusie",
        ignoreHelp: "Wycisza tylko ostrzeżenia. Nie naprawia przerwania pisania ani nie włącza ochrony. Przywrócisz ostrzeżenia w Ustawienia → Sterowanie → Rozwiązywanie problemów",
        sessionHelp: "Do wylogowania lub restartu Hyprlanda. Restart paska zachowuje ten wybór",
        allHelp: "Ukrywa ostrzeżenia także po kolejnym zalogowaniu, dopóki nie wyłączysz tej opcji",
        appHelp: "Dotyczy tej klasy aplikacji X11, także jej nowych okien. Aplikacje o tej samej klasie współdzielą ten wybór",
        detectedApps: "Aplikacje wykryte przy przerwaniu pisania", detectedHelp: "Te aplikacje mogą mieć związek z problemem, ale wykrycie nie jest dowodem przyczyny. Możesz osobno wyciszyć ostrzeżenia dla każdej z nich",
        historyPrivacy: "Historia pozostaje na Twoim urządzeniu. Tytuły okien i wpisywany tekst nie są zapisywane",
        noApps: "Nie zapisano jeszcze żadnej aplikacji. Przerwanie pisania można wykryć również bez ustalenia jego źródła", ignored: "Ostrzeżenia ignorowane", warningsOn: "Ostrzeżenia włączone",
        restoreApp: "Przywróć ostrzeżenia", ignoreAppAction: "Ignoruj ostrzeżenia", lastSeen: "Ostatnio wykryto: {date}",
        seenCount: "Zapisane przerwania pisania: {count}", classLabel: "Klasa aplikacji: {class}",
        appUncertain: "Podejrzewane źródło", globalOverride: "Ostrzeżenia są wyciszone powyżej. Aby przywrócić je dla aplikacji, wyłącz również ignorowanie dla sesji i wszystkich aplikacji",
        saveFailed: "Nie udało się zapisać wyboru. Poprzednie ustawienia pozostają bez zmian",
        notice: "Pisanie w wyszukiwarce zostało przerwane", review: "Zobacz możliwości",
        title: "Pisanie zostało przerwane",
        dialogCause: "Spróbuj dać jej oknu więcej miejsca lub przełączyć je w tryb pływający. Możesz też wybrać ochronę poniżej",
        dialogUnknown: "Wyszukiwarka utraciła wpisywanie, ale nie udało się ustalić źródła problemu",
        dialogUnknownHelp: "Spróbuj dać drugiemu oknu więcej miejsca lub przełączyć je w tryb pływający. Poniżej możesz też zatrzymać wpisywanie w wyszukiwarce",
        dialogApp: "Podejrzewana aplikacja: {app}",
        dialogSessionProtection: "Do ręcznego wyłączenia lub restartu paska. Przewijanie poza panelem wstrzymuje ochronę; gesty touchpada lub szybkie przewijanie mogą nie zostać przekazane",
        activeSessionTemporary: "Włączona do ręcznego wyłączenia lub restartu paska",
        dialogProtection: "Do zamknięcia tamtego okna. Przewijanie poza panelem wstrzymuje ochronę; touchpad i szybkie ruchy kółkiem mogą nie zadziałać",
        dialogKeep: "Utrzymuj fokus przy każdym wyszukiwaniu",
        dialogKeepHelp: "Blokuje przewijanie poza panelem. Kliknij poza nim lub Esc, aby go zamknąć; opcję wyłączysz w Rozwiązywaniu problemów",
        dialogDetails: "Rozwiązywanie problemów · szczegóły i ustawienia",
        cause: "{app} może przerywać pisanie. Jej okno wielokrotnie prosi o inny rozmiar. W niektórych wersjach Hyprlanda może to przekierować wpisywane znaki do okna pod kursorem zamiast do WindowPeek",
        limits: "Tymczasowa ochrona zatrzymuje wpisywanie w WindowPeek. Przewijanie poza panelem ją wstrzymuje; touchpad i szybkie ruchy kółkiem poza panelem mogą nie zadziałać. Kliknij panel, aby wrócić do pisania, lub naciśnij Esc, aby go zamknąć",
        alternatives: "Spróbuj dać temu oknu więcej miejsca, przełączyć je w tryb pływający albo zamknąć, gdy go nie używasz. Więcej miejsca może pomóc, jeśli aplikacja próbuje pomieścić swoją zawartość. Jeśli aplikacja obsługuje natywny Wayland, jej udokumentowany sposób uruchomienia też może pomóc",
        rsi: "RSI: instrukcja Wine Wayland (eksperymentalne)",
        scope: "Ochrona wyłączy się automatycznie po zamknięciu problematycznego okna",
        recoveryRetrying: "Przywracanie ochrony pisania…", recoveryPaused: "Ochrona pisania przerwana",
        recoveryUnavailable: "Ochrona pisania nadal jest włączona, ale nie udało się jej przywrócić. Kliknij Ponów w WindowPeek lub otwórz panel ponownie",
        retry: "Ponów", options: "Opcje", activeTitle: "Ochrona pisania",
        activeManual: "Włączona przy każdym wyszukiwaniu, niezależnie od otwartych aplikacji",
        activeTemporary: "Włączona do zamknięcia zatwierdzonego okna aplikacji",
        disableKeep: "Wyłącz ochronę pisania",
        confirmKeepTitle: "Chronić pisanie przy każdym wyszukiwaniu?", confirmKeep: "Włącz przy każdym wyszukiwaniu",
        confirmKeepBehavior: "Włącz tylko wtedy, gdy aplikacje często przerywają pisanie w wyszukiwarce. Blokuje przewijanie poza panelem; kliknij poza nim lub naciśnij Esc, aby go zamknąć",
        confirmKeepWhere: "Pozostaje włączona, aż wyłączysz Utrzymuj fokus wyszukiwania w Ustawienia → Sterowanie → Rozwiązywanie problemów",
        checking: "Sprawdzanie okna…",
        cancel: "Kontynuuj bez zmian", allow: "Włącz tymczasową ochronę",
        disabled: "Ochrona pisania wyłączona", enabled: "Ochrona pisania włączona", paused: "Ochrona pisania wstrzymana — kliknij panel, aby wznowić",
        stop: "Wyłącz", ended: "Ochrona wyłączona — problematyczne okno zostało zamknięte",
        stopped: "Tymczasowa ochrona została wyłączona", failed: "Nie udało się kontynuować tymczasowej ochrony",
        changed: "Okno zmieniło się lub nie można go sprawdzić — spróbuj ponownie",
        repeated: "Pisanie w wyszukiwarce jest ciągle przerywane",
        suggested: "Jeśli to przerywa pisanie, rozważ Utrzymuj fokus wyszukiwania w Ustawienia → Sterowanie → Rozwiązywanie problemów",
        manualEnabled: "Ochrona pisania włączona",
        settings: "Rozwiązywanie problemów i inne możliwości",
        keep: "Utrzymuj fokus wyszukiwania",
        when: "Włącz, jeśli po wyjechaniu kursorem poza wyszukiwarkę wpisywane znaki trafiają do innego okna. Pozostaw wyłączone, jeśli wyszukiwanie działa prawidłowo",
        behavior: "Utrzymuje wpisywanie w otwartym panelu wyszukiwania, również w przypiętym panelu kompaktowym. Blokuje przewijanie kółkiem i touchpadem poza panelem. Przewijanie wewnątrz nadal działa. Kliknij poza panelem lub naciśnij Esc, aby go zamknąć",
        lifetime: "Domyślnie wyłączone. Po włączeniu działa przy każdym otwarciu wyszukiwania, aż wyłączysz tę opcję tutaj. Nie blokuje fokusu podczas korzystania z Ustawień",
        causes: "Niektóre aplikacje, także uruchamiane przez Wine, wielokrotnie proszą o inny rozmiar okna. Gdy Hyprland utrzymuje je w układzie kafelkowym, może przekierować pisanie do okna pod kursorem. Przeszkadzać mogą też reguły aktywacji okien. Samo przerwanie pisania nie wskazuje winnej aplikacji",
        manualAlternatives: "Spróbuj dać temu oknu więcej miejsca lub przełączyć je w tryb pływający. Możesz też zamknąć je, gdy nie jest potrzebne, albo wypróbować udokumentowany tryb natywnego Wayland. Więcej miejsca może pomóc, jeśli aplikacja próbuje pomieścić swoją zawartość; nie jest to pewna naprawa",
        manualFailed: "Nie udało się uruchomić ochrony fokusu — zwykła obsługa pozostaje dostępna"
    }
};
function words(code) { return catalogs[code] || catalogs.en; }
